apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-elasticsearch
  labels:
    app: elasticsearch
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: {{ .Values.elasticsearch.replicas }}
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
          resources:
            {{- toYaml .Values.elasticsearch.resources | nindent 12 }}
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: {{ .Values.elasticsearch.javaOpts }}
            - name: cluster.routing.allocation.disk.threshold_enabled
              value: "false"
            - name: xpack.security.enabled
              value: "false"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-elasticsearch-pvc
