argilla:
  replicaCount: 1
  image:
    repository: argilla/argilla-server
    tag: latest
  resources:
    requests:
      cpu: "0.5"
    limits:
      cpu: "1"
  authSecretKey: "CHANGE_ME"

ingress:
  enabled: true
  className: "nginx"
  host: "argilla.local"

configmap:
  minikubeIP: "192.168.64.2"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

elasticsearch:
  enabled: false

externalElasticsearch:
  host: "argilla.local"
  port: 9200
  path: "/es"

serviceAccount:
  create: false