argilla:
  replicaCount: 1
  image:
    repository: argilla/argilla-server
    tag: latest
  resources:
    requests:
      cpu: "0.5"
    limits:
      cpu: "1"
  authSecretKey: "CHANGE_ME"
  auth:
    username: "argilla"
    password: "12345678"
    apiKey: "argilla.apikey"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2Gi
    mountPath: "/data"
  ingress:
    enabled: true
    className: "nginx"
    host: "argilla.local"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/use-regex: "true"
  configmap:
    minikubeIP: "192.168.49.2"
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50

# Elasticsearch installation is enabled by default.
# To disable it, set `elasticsearch.useOperator` to `false`
# and set `externalElasticsearch.host` to the host of your existing Elasticsearch instance.
elasticsearch:
  useOperator: true
  version: 8.5.3
  nodeCount: 1
  disableAuthentication: true
  resources:
    requests:
      cpu: 0.25
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  persistence:
    enabled: true
    storage:
      size: 1Gi
      accessModes:
      - ReadWriteOnce

externalElasticsearch:
  host: "argilla.local"
  port: 9200
  path: "/es"

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      resources:
        requests:
          cpu: 0.25
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
serviceAccount:
  create: false

worker:
  replicaCount: 1
  numWorkers: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
