apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argilla.fullname" . }}
  labels:
    {{- include "argilla.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.argilla.replicaCount }}
  selector:
    matchLabels:
      {{- include "argilla.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "argilla.selectorLabels" . | nindent 8 }}
    spec:
      {{- if not .Values.elasticsearch.enabled }}
      volumes:
        - name: hosts-file
          configMap:
            name: custom-hosts
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.argilla.image.repository }}:{{ .Values.argilla.image.tag }}"
          env:
            - name: ARGILLA_ELASTICSEARCH
              value: {{ if .Values.elasticsearch.enabled }}"http://{{ .Release.Name }}-elasticsearch:9200"{{ else }}"http://{{ .Values.externalElasticsearch.host }}/{{ .Values.externalElasticsearch.path }}"{{ end }}
            - name: ARGILLA_AUTH_SECRET_KEY
              value: {{ .Values.argilla.authSecretKey | quote }}
            - name: ARGILLA_REDIS_URL
              value: redis://{{ .Release.Name }}-redis-master:6379/0
            - name: USERNAME
              value: {{ .Values.argilla.auth.username }}
            - name: PASSWORD
              value: {{ .Values.argilla.auth.password }}
          ports:
            - containerPort: 6900
          {{- if not .Values.elasticsearch.enabled }}
          volumeMounts:
            - name: hosts-file
              mountPath: /etc/hosts
              subPath: hosts
          {{- end }}
          resources:
            {{- toYaml .Values.argilla.resources | nindent 12 }}
