version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - argilla
  argilla:
    image: argilla/argilla-server:releases-1.18.0
    restart: unless-stopped
    ports:
      - '6900:6900'
    environment:
      ARGILLA_ELASTICSEARCH: http://elasticsearch:9200
      ARGILLA_DATABASE_URL: postgresql://postgres:postgres@db:5432
      ARGILLA_LOCAL_AUTH_SECRET_KEY: ${ARGILLA_LOCAL_AUTH_SECRET_KEY:? Please generate a 32 character random string with `openssl rand -hex 32`}
      # ARGILLA_ENABLE_TELEMETRY: 0 # Opt-out for telemetry https://docs.argilla.io/en/latest/reference/telemetry.html

      # Set user configuration https://docs.argilla.io/en/latest/getting_started/installation/configurations/user_management.html
      # ARGILLA_LOCAL_AUTH_USERS_DB_FILE: /config/.users.yaml
      # volumes:
      #- ${PWD}/.users.yaml:/config/.users.yaml

      # DEFAULT_USER_ENABLED: false # Uncomment this line to disable the creation of the default user
      # DEFAULT_USER_PASSWORD: custom-password # Uncomment this line to set a custom password for the default user
      # DEFAULT_USER_API_KEY: custom-api-key # Uncomment this line to set a custom api-key for the default user
    networks:
      - argilla
    volumes:
      # ARGILLA_HOME_PATH is used to define where Argilla will save it's application data.
      # If you change ARGILLA_HOME_PATH value please copy that same value to argilladata volume too.
      - argilladata:/var/lib/argilla
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    environment:
      - node.name=elasticsearch
      - cluster.name=es-argilla-local
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - argilla
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - elasticdata:/usr/share/elasticsearch/data/

networks:
  argilla:
    driver: bridge

volumes:
  dbdata:
  argilladata:
  elasticdata:
