apiVersion: apps/v1
kind: Deployment
metadata:
  name: argilla-server-deployment
  labels:
    app: argilla-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argilla-server
  template:
    metadata:
      labels:
        app: argilla-server
    spec:
      initContainers:
        - name: wait-for-elasticsearch
          image: alpine/curl:latest
          command: [ "sh", "-c",
            "ELASTICSEARCH_URL='http://elasticsearch:9200'; status_code=$(curl -s -o /dev/null -w '%{http_code}' $ELASTICSEARCH_URL);
          while [ $status_code -ne 200 ]; do sleep 5; status_code=$(curl -s -o /dev/null -w '%{http_code}' $ELASTICSEARCH_URL);
          echo Sleeping...; done; echo Elasticsearch Connected " ]
      containers:
        - name: argilla-server
          image: argilla/argilla-server:latest
          env:
            - name: ARGILLA_ELASTICSEARCH
              value: "http://elasticsearch:9200"
            - name: ARGILLA_AUTH_SECRET_KEY
              value: "CHANGE_ME"
            - name: USERNAME
              value: "argilla"
            - name: PASSWORD
              value: "12345678"
          ports:
            - containerPort: 6900
          resources:
            requests:
              cpu: "0.5"
            limits:
              cpu: "1"
