name: Check repository files

on:
  workflow_call:
    outputs:
      pythonChanges:
        description: "True if some files in python code have changed"
        value: ${{ jobs.check-repo-files.outputs.pythonChanges }}
      end2endChanges:
        description: "True if some files in python code have changed"
        value: ${{ jobs.check-repo-files.outputs.end2endChanges }}
      buildChanges:
        description: "True if some files affecting the build have changed"
        value: ${{ jobs.check-repo-files.outputs.buildChanges }}
      frontendChanges:
        description: "True if some files affecting the frontend folder changed"
        value: ${{ jobs.check-repo-files.outputs.frontendChanges }}

jobs:
  check-repo-files:
    name: Check repo files
    runs-on: ubuntu-latest
    outputs:
      pythonChanges: ${{ steps.path_filter.outputs.pythonChanges }}
      buildChanges: ${{ steps.path_filter.outputs.buildChanges }}
      end2endChanges: ${{ steps.path_filter.outputs.end2endChanges }}
      frontendChanges: ${{ steps.path_filter.outputs.frontendChanges }}
    steps:

      - name: Checkout Code ðŸ›Ž
        uses: actions/checkout@v3

      - name: Check affected files
        uses: dorny/paths-filter@v3
        id: path_filter
        with:
          filters: |
            pythonChanges:
              - 'argilla/src/**'
              - 'argilla/tests/**'
              - 'argilla/pyproject.toml'
              - 'argilla/setup.py'
            end2endChanges:
              - 'argilla/src/**'
              - 'argilla/pyproject.toml'
              - 'argilla/setup.py'
              - 'scripts/end2end_examples.py'
              - 'docs/_source/tutorials_and_integrations/tutorials/feedback/end2end_examples/**'
            frontendChanges:
              - 'argilla-frontend/**'
            buildChanges:
              - 'argilla/src/**'
              - 'argilla-frontend/**'
              - 'argilla/pyproject.toml'
              - 'argilla/setup.py'
              - 'docker/**'
              - '.dockerignore'
              - '.github/workflows/**'
